# -*- coding: utf-8 -*-
"""Topik 3 4 - Rosyida Ishma Mardhiyyah.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CkuMZ4qb2U5rEMyaKH99tYGR8i1sFS5d

##Topic 3 - Python Structure & Data Type Assignment

# Data Type Declaration

1. > Create an empty variable (Points : 5)
"""

#Code goes here 
variable=""
variable

"""2. > Create a variable containing your name (Points : 5)"""

#Code goes here 
myname="Ishma"
myname

"""3. > Create a list of 5 items you can find in the classroom (Points : 5)"""

#Code goes here 
item=["table","chair","spidol","whiteboard","book"]
item

"""4. > Create a dictionary containing 2 keys and value (Points : 5)"""

#Code goes here
items={"name":["table","book"],
       "color":["brown","white"]}
items

"""# Basic Data Operation

You sold 20 pieces of electronics at the price of 12000. The customer gets a total discount of 10%.

Below are those variables:

1.   price=12000
2.   quantity_sold=20
3.   discount=10%


Using Python code, write the code the find the total money that the customer to pay. (Points : 15)
"""

#Code goes here 
price=12000
quantity_sold=20
discount=0.1

disc=price*quantity_sold*discount
total_payment=price*quantity_sold-disc
print(total_payment)

"""# List Data Operation

5. > Follow the instructions in the code blocks
"""

# Create list of countries in the world (total 7 countries) (Points : 5)

#Code goes here 
countries=["Indonesia","Rusia","Amerika","Perancis","Jerman","Korea","Turki"]

# Get 4 countries from the first index of the list (Points : 5)

#Code goes here
countries[0:4]

# Append new country to the list (Points : 5)

#Code goes here
countries.append("Singapura")
countries

# Drop one country from the list (Points : 5)

#Code goes here
countries.remove("Perancis")
countries

# Get country in the last index (Points : 5)

#Code goes here
#Ada 2 step yang harus dilakukan dalam menjawab soal ini
#Step 1: Menghitung list length untuk mengetahui index ke berapa yang menjadi index terkahir
len(countries)

#Step 2: Memanggil elemen index terakhir dalam countries list berdasarkan step 1
countries[6]

"""# Dictionary Data Operation

6. >  Follow the instructions below
"""

# Given the dictionary below

customer={
    "name":['Dio','Eka','Wayu','Riki'],
    "age":[20,19,24,39],
    "gender":[1,0,0,1],
    "membership":['Platinum','Gold','Silver','Silver']
}

# Print all keys in customer (Points : 5)

#Code goes here
dict.keys(customer)

# Print all customer names (Points : 5)

#Code goes here
customer["name"]

# Print the first customer name (Points : 5)

#Code goes here
customer["name"][0]

# Drop "age" key from the dictionary (Points : 5)

#Code goes here
del customer["age"]
customer

# Replace customer gender list value (Points : 20)
# gender 1 => Male
# gender 0 => Female 


#Code goes here
customer["gender"]=["Male","Female","Female","Male"]
customer

"""Soal replace customer gender di atas juga bisa diselesaikan dengan automasi sebagai berikut."""

# Step 1: Mendefinisikan ulang dictionary customer sebelum diubah dengan coding di atas
customer={
    'name': ['Dio', 'Eka', 'Wayu', 'Riki'],
    'gender': [1, 0, 0, 1],
    'membership': ['Platinum', 'Gold', 'Silver', 'Silver']
    }
customer

# Step 2: Menghitung list length dari gender list value
len(customer["gender"])

# Step 3: Mengubah elemen gender list, 0 menjadi Female dan 1 menjadi Male
new_gender=[]
for i in range(0,4):
  if customer["gender"][i]==1:
   new_gender.append("Male")
  else:
   new_gender.append("Female")
new_gender

# Step 4: Menghapus gender list 
del customer["gender"]
# Step 5: Memasukkan list new_gender ke dalam dictionary customer
customer.update({"gender":new_gender})
customer